### ISSUE TITLE
The game crashes after disconnect when you're tracking players in the spectator mode

### ISSUE THREAD

**Issue by Alprnn357** [Velaron/cs16-client#63]
Hi, dear "cs16-client" player. :)

Since developers are too busy, we don't have too much time to work with each bug of each user.

So before you will press *Submit* button, make sure you have checked all the paragraphs below:
- [x] I installed latest versions of cs16-client and Xash3D port. (look here: https://github.com/Velaron/cs16-client/releases and https://github.com/Velaron/xash3d-fwgs/releases)
- [x] I installed fresh game data from my Steam account.
- [x] I looked through the Issues section of this repository.
- [x] I looked through the Issues section of https://github.com/FWGS/xash3d repository.
- [x] I looked through the Issues section of https://github.com/FWGS/xash3d-android-project repository.

You are still here? Great! This means that you have a new bug. But this is not the end. For our mutual understanding, we require some data from you:
- [x] Short description of your problem.
CS16Client New Engine crashes after disconnect when you're tracking players in the spectator mode.
- [x] Information about your device: RAM size, CPU, GPU and OS. 
Device: Samsung Galaxy J7 2016 (j7xelte)
Android version: 8.1.0 (armeabi-v7a)
Game files: Taken from Steam
- [x] engine.log. You can find that in your "xash" folder. If there is not log, re-run game with "-log" command line parameter. 
[engine.log](https://github.com/Velaron/cs16-client/files/13383183/engine.log)

- [x] adb logcat. Isn't necessary, but it will be very nice, if you can post this. You can ask Google for "How to get the "logcat" data", if you don't know what is it.
[logcat-cs16clientbeta.txt](https://github.com/Velaron/cs16-client/files/13383188/logcat-cs16clientbeta.txt)

https://github.com/Velaron/cs16-client/assets/37711793/03a0e55c-b410-40c2-95fc-ab5cfd85dc18

**Comment by Alprnn357** [comment]
Tried to change video renderers to GL4ES and GLES1 (NanoGL). But it didn't fix this issue.

**Comment by Alprnn357** [comment]
Tried to change the video renderer from GL4ES to GLES1 (NanoGL). But it didn't fix this issue.

**Comment by Vladislav4KZ** [comment]
Same for me too.

Samsung Galaxy A52 (SM-A525F)
Android 13, OneUI 5.1

**Comment by Vladislav4KZ** [comment]
Now I've retested it, the game just crashes when disconnected from the server.

**Comment by Vladislav4KZ** [comment]
I tested today and the bug wasn't reproduced.

Tested on:
Xash3D FWGS v49/0.20
Build number: 3249
Build type: android-arm64
Commit: https://github.com/FWGS/xash3d-fwgs/commit/abdff6eff68825a0e3124a6b5ed2f5cd77df0a2d
Branch: master

I also used the cs16-client fork by jeefo with the updated YaPB.

Device: Samsung Galaxy A52 (SM-A525F)
OS: Android 14 (OneUI 6.0)
